### ISSUE TITLE
random error swift-container-sync 

### ISSUE THREAD

**Issue by dbourasseau** [dngroup/t-nova#2]
one of two CDN are this error

```
ID: swift-container-sync
    Function: service.running
      Result: False
     Comment: Service swift-container-sync failed to start
     Started: 18:24:00.829702
    Duration: 1572.129 ms
     Changes:   
```
